In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf

C:\Users\Derrick\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:23: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  data_klasses = (pandas.Series, pandas.DataFrame, pandas.Panel)

In [14]:
NominalGDP = pd.read_csv('PH GDP USD.csv')
NominalGDP = NominalGDP.iloc[27:,[0,1]]

   Unnamed: 0     PH: GDP: USD
27       1962    4399.82776797
28       1963    4875.30986634
29       1964    5271.40466837
30       1965    5784.39897698
31       1966    6371.45930441
32       1967    6809.13423554
33       1968    7591.60305344
34       1969    8408.22969914
35       1970    6687.20483437
36       1971    7408.30573565
37       1972     8017.4686882
38       1973   10082.88560307
39       1974   13781.13996965
40       1975   14893.96928766
41       1976    17097.5632703
42       1977   19648.10612201
43       1978    22706.1554753
44       1979   27502.16872696
45       1980   32450.54184307
46       1981   35646.41695254
47       1982   37140.16393443
48       1983   33212.18065817
49       1984   31408.49287669
50       1985   30734.33544899
51       1986   29868.33908083
52       1987    33195.9334296
53       1988   37885.44041868
54       1989   42575.18390556
55       1990   44311.59375578
56       1991   45417.56130225
57       1992   52976.34492896
58       1993   54368.08395311
59       1994   64084.46012446
60       1995    74119.9872445
61       1996   82848.14061803
62       1997   82344.26057067
63       1998   72207.02876776
64       1999   82995.14579293
65       2000   83670.26170773
66       2001   78921.07149825
67       2002    84307.3698679
68       2003   87039.14596501
69       2004   95001.99459956
70       2005  107419.98640019
71       2006  127652.90895484
72       2007  155980.40807167
73       2008   181006.8599074
74       2009  176131.65490991
75       2010  208368.89231865
76       2011  234216.73070349
77       2012  261920.54260612
78       2013  283902.82972016
79       2014  297483.55329948
80       2015  306445.87163148
81       2016  318627.00396549
82       2017  328480.73814773
83       2018  346841.89688955
84       2019  376795.50867968